apiVersion: v1
kind: Service
metadata:
  name: tira-discourse
spec:
  type: NodePort
  selector:
    app: tira-discourse
  ports:
    - nodePort: 30802
      port: 9292
      targetPort: 9292
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tira-discourse
spec:
  selector:
    matchLabels:
      app: tira-discourse
  replicas: 1
  template:
    metadata:
      labels:
        app: tira-discourse
    spec:
      containers:
      - name: tira-discourse
        image: discourse/discourse_dev:release
        ports:
          - hostIP: 0.0.0.0
            hostPort: 9292
            containerPort: 9292
        volumeMounts:
          - mountPath: "/shared/postgres_data"
            name: discourse-postgres-data
          - mountPath: "/src"
            name: discourse-src-code
          - mountPath: "/init-discourse.sh"
            name: init-discourse
        lifecycle:
          postStart:
            exec:
